# Generated by Django 5.2.5 on 2025-09-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clickify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clicklog",
            name="ref",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="trackedlink",
            name="target_url",
            field=models.URLField(
                blank=True,
                help_text="The actual URL to the destination (e.g., on S3, a blog post, an affiliate link, etc.) - Not mandatory",
                max_length=2048,
                null=True,
            ),
        ),
    ]
